name: weather_app_with_clean_architecture
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  http: ^1.2.2
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  internet_connection_checker: ^2.0.0
  internet_connection_checker_plus: ^2.5.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
